trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
    path: $(MAVEN_CACHE_FOLDER)

- script: |
    mvn -B -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) clean package -DskipTests
  displayName: 'Build WAR with Maven (Skip Tests)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/*.war'
    artifactName: 'springboot-war'
    publishLocation: 'Container'
