trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: TestAzureCLI
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'RG-Devansh-POC-0041'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Successfully connected to Azure!"
