trigger: none
pr: none

parameters:
  - name: relVersion
    type: string
    default: '1.0.0-SNAPSHOT'

stages:
  - stage: Release
    displayName: "Release Stage"
    jobs:
      - template: templates/releaseByModule.yaml
        parameters:
          projectName: 'AGF.com-POC'    # required
          repoName: 'spring-petclinic'          # required
          branchName: 'main'                # required, or your branch name
          jobName: 'ReleaseJob'             # required, any valid string
          module: '.'                      # optional, your module path
          relVersion: ${{ parameters.relVersion }}
