name: 'oci-image-builder'

trigger: none  # Prevent manual/automatic trigger from commits

resources:
  pipelines:
    - pipeline: buildWarPipeline
      source: devansha-optimus.spring-petclinic-buildwar
      trigger: true

variables:
  ACR_NAME: azurespringapp
  ACR_LOGIN_SERVER: azurespringapp.azurecr.io
  IMAGE_NAME: springboot-app
  BUILDER: azurespringapp.azurecr.io/azure-spring-builder:latest
  AZURE_SERVICE_CONNECTION: 'RG-Devansh-POC-0041'

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndPushImage
  displayName: 'Build and Push OCI Image'
  steps:

    - download: buildWarPipeline
      artifact: springboot-war

    - script: |
        echo "Downloading pack CLI v0.32.0..."
        curl -sSL -o pack.tgz https://github.com/buildpacks/pack/releases/download/v0.32.0/pack-v0.32.0-linux.tgz
        tar -xzf pack.tgz
        sudo mv pack /usr/local/bin/
      displayName: 'Install pack CLI'

    - task: AzureCLI@2
      displayName: 'Login to ACR'
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $ACR_NAME
      env:
        ACR_NAME: $(ACR_NAME)

    - script: |
        echo "Finding WAR file..."
        WAR_FILE=$(find $(Pipeline.Workspace)/buildWarPipeline/springboot-war -name "*.war" | head -n 1)
        echo "WAR file located: $WAR_FILE"

        echo "Extracting version from WAR file name..."
        FILENAME=$(basename "$WAR_FILE")
        # Assuming format: my-service-2.5.war
        VERSION=$(echo "$FILENAME" | sed -E 's/.*-([0-9]+\.[0-9]+)\.war/\1/')
        echo "Extracted version: $VERSION"

        echo "##vso[task.setvariable variable=WAR_FILE]$WAR_FILE"
        echo "##vso[task.setvariable variable=VERSION]$VERSION"
      displayName: 'Locate WAR and extract version'

    - script: |
        echo "Building OCI image using Paketo Buildpacks..."
        echo "Using WAR file: $(WAR_FILE)"
        echo "Using tag version: $(VERSION)"
        
        pack build $ACR_LOGIN_SERVER/$IMAGE_NAME:$(VERSION) \
          --path $(WAR_FILE) \
          --builder $BUILDER \
          --publish
      displayName: 'Build and push OCI image with extracted version'
