trigger:
  branches:
    include:
      - main

variables:
  ACR_NAME: azurespringapp.azurecr.io            # Replace with your ACR login server
  IMAGE_NAME: springboot-app                 # Replace with your desired image name
  BUILDER: gcr.io/paketo-buildpacks/enterprise-builder     # Or your enterprise builder image
  WAR_FILE: target/demo-3.2.0.war                   # Adjust if needed
  AZURE_SERVICE_CONNECTION: RG-Devansh-POC-0041  # Your existing azurerm service connection name

stages:
  - stage: BuildAndPush
    displayName: Build and Push OCI Image
    jobs:
      - job: BuildImage
        displayName: Build OCI Image using Paketo
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: Checkout@1

          - script: |
              echo "Installing pack CLI..."
              curl -sSL "https://github.com/buildpacks/pack/releases/latest/download/pack-linux.tgz" | tar -xz
              sudo mv pack /usr/local/bin/
            displayName: 'Install pack CLI'

          - script: |
              echo "Checking for WAR file at ${{ variables.WAR_FILE }}..."
              ls -l ${{ variables.WAR_FILE }}
            displayName: 'Verify WAR file'

          - task: AzureCLI@2
            displayName: 'Login to Azure and ACR'
            inputs:
              azureSubscription: ${{ variables.AZURE_SERVICE_CONNECTION }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Logging into ACR..."
                az acr login --name $ACR_NAME

          - script: |
              echo "Building and publishing image..."
              pack build ${{ variables.ACR_NAME }}/${{ variables.IMAGE_NAME }}:$(Build.BuildId) \
                --path ${{ variables.WAR_FILE }} \
                --builder ${{ variables.BUILDER }} \
                --publish
            displayName: 'Build and Push using Paketo'
