trigger: none
pr: none

parameters:
  - name: relVersion
    type: string
    default: '1.0.1-SNAPSHOT'

stages:
  - stage: Release
    displayName: "Release Stage"
    jobs:
      - template: ./templates/releaseByModule.yaml
        parameters:
          module: '.'
          relVersion: ${{ parameters.relVersion }}
          jobName: ReleaseJob
          projectName: AGF.com-POC
          repoName: spring-petclinic
          branchName: main
