name: oci-image-builder

trigger: none  # Triggered by pipeline resource

resources:
  pipelines:
    - pipeline: buildWarPipeline
      source: devansha-optimus.spring-petclinic-buildwar   # Use actual pipeline name here
      trigger: true

variables:
  ACR_NAME: $(var-acrName)
  ACR_LOGIN_SERVER: $(var-acrLoginServer)
  IMAGE_NAME: $(var-imgName)
  BUILDER: azurespringapp.azurecr.io/azure-spring-builder:latest
  AZURE_SERVICE_CONNECTION: 'RG-Devansh-POC-0041'
  APP_NAME: my-service

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildScanPushOCI
  displayName: 'Build, Scan and Push OCI Image'
  steps:

    - download: buildWarPipeline
      artifact: springboot-war

    - script: |
        echo "Downloading pack CLI v0.32.0..."
        curl -sSL -o pack.tgz https://github.com/buildpacks/pack/releases/download/v0.32.0/pack-v0.32.0-linux.tgz
        tar -xzf pack.tgz
        sudo mv pack /usr/local/bin/
      displayName: 'Install pack CLI'

    - task: AzureCLI@2
      displayName: 'Login to ACR'
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $ACR_NAME

    - script: |
        echo "Finding WAR file in downloaded artifact..."
        WAR_FILE=$(find $(Pipeline.Workspace)/buildWarPipeline/springboot-war -name "*.war" | head -n 1)
        echo "WAR file located: $WAR_FILE"

        BASENAME=$(basename "$WAR_FILE")
        echo "WAR file basename: $BASENAME"

        # Extract version from WAR filename assuming format: <app-name>-<version>.war
        APP_NAME="$(APP_NAME)"
        VERSION="${BASENAME#${APP_NAME}-}"
        VERSION="${VERSION%.war}"
        echo "Extracted version: $VERSION"
        echo "##vso[task.setvariable variable=IMAGE_VERSION]$VERSION"

        echo "Building OCI image using Paketo Buildpacks..."
        pack build $ACR_LOGIN_SERVER/$IMAGE_NAME:$VERSION \
          --path "$WAR_FILE" \
          --builder $BUILDER \
          --pull-policy if-not-present
      displayName: 'Build image and extract version'

    - task: Trivy@1
      displayName: 'Trivy Scan - JSON'
      inputs:
        image: '$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_VERSION)'
        format: 'json'
        output: 'trivy-report.json'
        severity: 'CRITICAL,HIGH'
        exitCode: '0'
        ignoreUnfixed: true

    - task: Trivy@1
      displayName: 'Trivy Scan - Table'
      inputs:
        image: '$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_VERSION)'
        format: 'table'
        output: 'trivy-report.txt'
        severity: 'CRITICAL,HIGH'
        exitCode: '0'
        ignoreUnfixed: true

    - task: Trivy@1
      displayName: 'Trivy Scan - SARIF'
      inputs:
        image: '$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_VERSION)'
        format: 'sarif'
        output: 'trivy-report.sarif'
        severity: 'CRITICAL,HIGH'
        exitCode: '0'
        ignoreUnfixed: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Trivy Reports'
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)'
        artifactName: 'trivy-reports'
        publishLocation: 'Container'

    - task: AzureCLI@2
      displayName: 'Push Image to ACR'
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Pushing image to ACR..."
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$(IMAGE_VERSION)
