trigger:
  branches:
    include:
      - main

variables:
  # ACR and image details
  ACR_NAME: azurespringapp.azurecr.io
  IMAGE_NAME: springboot-app
  BUILDER: gcr.io/paketo-buildpacks/enterprise-builder
  WAR_FILE: target/demo-3.2.0.war
  DOCKER_REGISTRY_SERVICE_CONNECTION: RG-Devansh-POC-0041

stages:
  - stage: BuildAndPush
    displayName: Build and Push OCI Image
    jobs:
      - job: BuildImage
        displayName: Build OCI Image using Paketo
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: Checkout@1

          - script: |
              echo "Installing pack CLI..."
              curl -sSL "https://github.com/buildpacks/pack/releases/latest/download/pack-linux.tgz" | tar -xz
              sudo mv pack /usr/local/bin/
            displayName: 'Install pack CLI'

          - script: |
              echo "Checking for WAR file at ${{ variables.WAR_FILE }}..."
              ls -l ${{ variables.WAR_FILE }}
            displayName: 'Verify WAR file'

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: 'login'
              containerRegistry: ${{ variables.DOCKER_REGISTRY_SERVICE_CONNECTION }}

          - script: |
              echo "Building and publishing image..."
              pack build ${{ variables.ACR_NAME }}/${{ variables.IMAGE_NAME }}:$(Build.BuildId) \
                --path ${{ variables.WAR_FILE }} \
                --builder ${{ variables.BUILDER }} \
                --publish
            displayName: 'Build and Push using Paketo'
