trigger:
  branches:
    include:
      - main

variables:
  AZURE_SERVICE_CONNECTION: RG-Devansh-POC-0041

stages:
  - stage: Test
    jobs:
      - job: Hello
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Hello from Azure CLI task"
