trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'target/*.war'
      - 'pom.xml'
      - '**/*.java'

variables:
  ACR_NAME: azurespringapp
  ACR_LOGIN_SERVER: azurespringapp.azurecr.io
  IMAGE_NAME: springboot-app
  BUILDER: gcr.io/paketo-buildpacks/enterprise-builder
  AZURE_SERVICE_CONNECTION: 'RG-Devansh-POC-0041' 

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BuildAndPushImage
    displayName: Build and Push OCI Image
    steps:
      - checkout: self

      # Optional: if you want to ensure WAR exists, otherwise skip this
      - script: |
          echo "Checking if WAR file exists in target directory..."
          ls -l target/*.war
        displayName: 'Check WAR file'

      - script: |
          echo "Installing pack CLI..."
          curl -sSL "https://github.com/buildpacks/pack/releases/latest/download/pack-linux.tgz" | tar -xz
          sudo mv pack /usr/local/bin/
        displayName: 'Install pack CLI'

      - task: AzureCLI@2
        displayName: 'Login to Azure Container Registry'
        inputs:
          azureSubscription: $(AZURE_SERVICE_CONNECTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Logging into ACR: $ACR_NAME"
            az acr login --name $ACR_NAME
        env:
          ACR_NAME: $(ACR_NAME)

      - script: |
          WAR_FILE=$(find target -name "*.war" | head -n 1)
          echo "WAR file located at: $WAR_FILE"
          
          echo "Building and pushing image with tag: $(Build.BuildId)"
          pack build $ACR_LOGIN_SERVER/$IMAGE_NAME:$(Build.BuildId) \
            --path $WAR_FILE \
            --builder $BUILDER \
            --publish

          echo "Tagging image as latest"
          docker tag $ACR_LOGIN_SERVER/$IMAGE_NAME:$(Build.BuildId) $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

          echo "Pushing latest tag to ACR"
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
        displayName: 'Build and Push OCI Image'
        env:
          ACR_LOGIN_SERVER: $(ACR_LOGIN_SERVER)
          IMAGE_NAME: $(IMAGE_NAME)
          BUILDER: $(BUILDER)
