eureka:
  client:
    service-url:
      defaultZone: https://serviceregistry-azure-java.ext.calmwave-25ab1c98.canadacentral.azurecontainerapps.io
    register-with-eureka: true
    fetch-registry: true
    tls:
      enabled: false
  instance:
    prefer-ip-address: true
    hostname: azure-springapp-env.canadacentral.azurecontainerapps.io

spring:
  boot:
    admin:
      client:
        url: https://springapp-admin-azure-java.ext.calmwave-25ab1c98.canadacentral.azurecontainerapps.io
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
