parameters:
  - name: module
    type: string
  - name: relVersion
    type: string
  - name: jobName
    type: string
  - name: projectName
    type: string
  - name: repoName
    type: string
  - name: branchName
    type: string

jobs:
- job: ${{ parameters.jobName }}
  displayName: "Release ${{ parameters.module }} version ${{ parameters.relVersion }}"
  steps:
    - script: echo "Releasing module ${{ parameters.module }} version ${{ parameters.relVersion }}"
